<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SsrOracle.Core.CompileOnly</AssemblyName>
    <BaseOutputPath>bin/core-net35/</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Core/**/*.cs" LinkBase="Core" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35"
                      Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
